spring.application.name=Auth-Service
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/auth-service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
server.port=8080
jwt.secret=K8f9s1zLw7QpG3vBnEtR4mYxP0uDdFsHWc123456
jwt.expiration=18000000