spring.application.name=api-gateway
server.port=8086
jwt.secret=K8f9s1zLw7QpG3vBnEtR4mYxP0uDdFsHWc123456

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**


# Example: PROFILE SERVICE (change port/path to your actual service)
spring.cloud.gateway.routes[1].id=profile-service
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/profiles/**